# baseURL = "https://if001.github.io/if-blog-hugo/"
baseURL = "https://www.if-blog.site"

languageCode = "ja"
title = "アンドロイドは推理小説を書くか?"
theme = "my_harbor"

DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
publishDir= "docs"
googleAnalytics = "UA-127416809-1"
pluralizeListTitles = false
ignoreFiles = ["/posts/*/\\.#*"]

[author]
  name = "if_004"
  discription = "自然言語処理を中心に技術系の記事を書いていきます。最終的には、AIに推理小説を書かせたい。普段はフロント/バックエンド開発。コメントはtwitterにお願いします。"
  language = ["scala", "golang", "python", "vue.js", "angular", "react", "elisp"]

[params]
  description="自然言語処理を中心に技術系の記事を書いていきます。最終的には、AIに推理小説を書かせたい。普段はフロント/バックエンド開発。"

[outputs]
  section = ["JSON", "HTML"]
 
[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
    
hasCJKLanguage = true

[blackfriday]
   hrefTargetBlank = true
   
[[params.nav]]
  identifier = "home"
  name = "Home"
  icon = "fas fa-home fa-lg"
  url = "/"
  weight = 3
  
[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "pages/about"
  weight = 3
  
[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3
  
[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "pages/search"
  weight = 3
  
[[params.social]]
  name= "twitter"
  url="https://twitter.com/if_004"
  icon="fab fa-twitter"

[related]
  includeNewer = true
  threshold = 20
  toLower = true

[[related.indices]]
  name = "tags"
  weight = 100

[[related.indices]]
  name = "date"
  weight = 10

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
